### ISSUE TITLE
Export / Import - data in cvs and others, from mespronos

### ISSUE THREAD

**Issue by mannunes** [kgaut/mespronos#109]
We already have an Import feature, but we should be able to export selected divisions setup data, to have a BLANK file that we could see the fields needed, or we could use the data to export to another website, to spawn websites using this extension, so more friends could help..

**Comment by kgaut** [comment]
Hi, for a start you could have a look to the files under `assets/examples` that i'm using to populate data.

An export features would be great indeed.

regards.

**Comment by kgaut** [comment]
See #113
