### ISSUE TITLE
Import Mondial 2018 - The "group" entity type does not exist

### ISSUE THREAD

**Issue by webaliz** [kgaut/mespronos#114]
J'ai importé sur mon site, les templates des 3 journées de pool et lorsque je veux accéder à MONURL/fr/mespronos/leagues/1
J'ai cette erreur :

Drupal\Component\Plugin\Exception\PluginNotFoundException : The "group" entity type does not exist. dans Drupal\Core\Entity\EntityTypeManager->getDefinition() (ligne 133 de /srv/bindings/ef26e85135da4bd5958ef0bbf86e6eb7/code/core/lib/Drupal/Core/Entity/EntityTypeManager.php).

**Comment by kgaut** [comment]
Bonjour,
Merci du rapport de bug !
ça devrait être corrigé dans la dernière version, tenez-moi au courant !

**Comment by webaliz** [comment]
On y est presque... Mais pas encore tout à fait ;)

> Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException : You have requested a non-existent service "mespronos.domain_manager". dans Drupal\Component\DependencyInjection\Container->get() (ligne 151 de /srv/bindings/ef26e85135da4bd5958ef0bbf86e6eb7/code/core/lib/Drupal/Component/DependencyInjection/Container.php).

**Comment by kgaut** [comment]
Toujours sur la même page ?

**Comment by webaliz** [comment]
Oui, tout à fait...

**Comment by kgaut** [comment]
Corrigé pour de bon :)

**Comment by webaliz** [comment]
Navré mais après remplacement du dossier "src" :
<img width="1170" alt="capture d ecran 2018-05-15 a 10 41 40" src="https://user-images.githubusercontent.com/39271910/40046302-ec94b262-582c-11e8-9ed2-eb6909752bf7.png">

**Comment by kgaut** [comment]
Depuis où récupérez-vous le module ? et quelle version ?

**Comment by webaliz** [comment]
`git clone https://github.com/mespronos/mespronos.git`

**Comment by kgaut** [comment]
C'est étrange, ce service est défini dans le fichier `mespronos.services.yml`

voici le contenu de ce fichier : https://github.com/mespronos/mespronos/blob/8.x-1.x/mespronos.services.yml

il correspond bien à ce que vous avez dans votre fichier ?

**Comment by webaliz** [comment]
Bonne nouvelle : après un reimport de TOUS les fichiers du module, tout est rentré dans l'ordre.
Je continue mes tests et vous ferai part de toute nouvelle découverte.
Bravo pour ce module aussi original que ludique ;)

**Comment by webaliz** [comment]
Je me charge aussi de le traduire, apparement, ce n'est pas fait ;)

**Comment by kgaut** [comment]
Super !
Si je l'ai traduit pour mon site principal : https://mespronos.net, je peux vous préparer un fichier po contenant les traductions à jour.
(un ancien est déjà présent dans le module : `mespronos/config/translations/fr.po`) à importer via le BO.
