### ISSUE TITLE
Teams logo edit

### ISSUE THREAD

**Issue by webaliz** [kgaut/mespronos#115]
Il semble qu'il soit impossible de créer/modifier le logo d'une équipe :
<img width="896" alt="capture d ecran 2018-05-19 a 13 27 43" src="https://user-images.githubusercontent.com/39271910/40268135-a4bd8c5e-5b68-11e8-828b-fc4db6b81289.png">
<img width="818" alt="capture d ecran 2018-05-19 a 13 27 12" src="https://user-images.githubusercontent.com/39271910/40268136-a4dc5c9c-5b68-11e8-87ef-32af74f0143f.png">
<img width="571" alt="capture d ecran 2018-05-19 a 13 27 02" src="https://user-images.githubusercontent.com/39271910/40268137-a4f81b94-5b68-11e8-82b2-eb9ea89c1979.png">

**Comment by kgaut** [comment]
Effectivement il manquait dans la configuration du formulaire du type d'entité « équipe » je viens de l'ajouter : 
https://github.com/mespronos/mespronos/commit/dc52a549e7f11ec6c312702fcf4a877b56c58f8f
Pour que ça soir effectif chez vous 3 solutions

1. Réinstallation du module (un peu bourrin)
2. Création de ce fichier de configuration dans la configuration de votre site (si vous êtes à l'aise avec CMI)
3. Modification directement de la config en BO via le chemin `/admin/mespronos/structure/team/form-display` : 
Avant : 
![2018-05-19-13-56-10-screenshot-01](https://user-images.githubusercontent.com/736910/40268375-ad817be6-5b5b-11e8-9fb2-9c79cbd32528.jpg)
Après : 
![2018-05-19-13-56-19-screenshot-01](https://user-images.githubusercontent.com/736910/40268378-b2adcc6e-5b5b-11e8-98ba-82ba6b750b1a.jpg)
