### ISSUE TITLE
The website encountered an unexpected error.

### ISSUE THREAD

**Issue by tbone99** [kgaut/mespronos#117]
After installation of MesPronos module and game data imported. (I did not install the MesPronos Group module though).  A game prediction was placed, game time passes, then site throws this error on any page visited:   
The website encountered an unexpected error. Please try again later.

The log message is: 
  Drupal\Core\Database\InvalidQueryException: Query condition 'file_managed.uuid IN ()' cannot be empty. in Drupal\Core\Database\Query\Condition->condition() (line 103 of /home/admin/public_html/drupal8/core/lib/Drupal/Core/Database/Query/Condition.php).

line 103 of Condition.php is:
     throw new InvalidQueryException(sprintf("Query condition '%s %s ()' cannot be empty.", $field, $operator));

Could you provide some direction on how to fix?  Thanks.

**Comment by tbone99** [comment]
Repaired by rolling back this change in src/Controller/UserController.php

https://github.com/mespronos/mespronos/commit/4566eede0a7b9ac531a4ecafa4e07f3f8c615033#diff-2e6355de36175249110ad2b48562407a

**Comment by kgaut** [comment]
sorry for the delay :) 

fresh install should works now
